version: '3.8'

services:
  # Backend service for both environments
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: admin-ui-backend-${NODE_ENV:-production}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
    volumes:
      - ./backend/.env:/app/.env:ro
      # Mount source code for development
      - ${DEV_BACKEND_VOLUME:-empty_volume}:/app/src
      - ${DEV_BACKEND_NODE_MODULES:-empty_volume}:/app/node_modules
    networks:
      - admin-ui-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service for development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: admin-ui-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - admin-ui-network
    restart: unless-stopped
    profiles:
      - dev
    stdin_open: true
    tty: true

  # Frontend service for production
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: admin-ui-frontend-prod
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - admin-ui-network
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  admin-ui-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
  empty_volume:
